<?php

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

defined('BASEPATH') OR exit('No direct script access allowed');

class Exporter extends CI_Model
{
    /**
     * Export data from array.
     *
     * @param $title
     * @param $data
     * @param bool $download
     * @param null $storeTo
     * @return null|string
     */
    public function exportFromArray($title, $data, $download = true, $storeTo = null)
    {
        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setCreator($this->config->item('app_name'))
            ->setLastModifiedBy($this->config->item('app_name'))
            ->setTitle($title)
            ->setSubject('Data export: ' . $title)
            ->setDescription('Data export generated by: ' . $this->config->item('app_name'));

        $excelWriter = new Xlsx($spreadsheet);

        try {
            $spreadsheet->setActiveSheetIndex(0);
            $activeSheet = $spreadsheet->getActiveSheet();

            $activeSheet->setCellValue('A1', $title)
                ->getStyle('A1')
                ->getFont()
                ->setBold(true);

            $header = [];
            if (!empty($data)) {
                $header = array_keys($data[0]);
                $header = array_map(function ($title) {
                    return strtoupper(str_replace(['_', '-'], ' ', $title));
                }, $header);
            }

            $activeSheet->fromArray($header, null, 'A1');
            $activeSheet->fromArray($data, null, 'A2');

            $columnIterator = $spreadsheet->getActiveSheet()->getColumnIterator();
            foreach ($columnIterator as $column) {
                $spreadsheet->getActiveSheet()
                    ->getColumnDimension($column->getColumnIndex())
                    ->setAutoSize(true);

                $spreadsheet->getActiveSheet()
                    ->getStyle($column->getColumnIndex() . '1')
                    ->applyFromArray([
                            'fill' => [
                                'fillType' => Fill::FILL_SOLID,
                                'color' => ['rgb' => '000000']
                            ],
                            'font' => [
                                'bold' => true,
                                'color' => ['rgb' => 'FFFFFF']
                            ]
                        ]
                    );
            }

            if ($download) {
                $this->load->helper('download');
                $storeTo = './uploads/temp/' . $title . '-' . uniqid() . '.xlsx';
                $excelWriter->save($storeTo);
                force_download($storeTo, null, true);
            } else {
                if (empty($storeTo)) {
                    $storeTo = './uploads/temp/' . $title . '-' . uniqid() . '.xlsx';
                }
                $excelWriter->save($storeTo);
                return $storeTo;
            }

        } catch (\PhpOffice\PhpSpreadsheet\Exception $e) {
            return $e->getMessage();
        }

        return false;
    }

    /**
     * Export pdf from html.
     *
     * @param $title
     * @param $html
     */
    public function exportToPdf($title, $html)
    {
        $pdf = new \Dompdf\Dompdf(['isHtml5ParserEnabled' => true]);
        $pdf->loadHtml($html);
        $pdf->setPaper('A4', 'portrait');
        $pdf->render();
        $pdf->stream($title . ".pdf", array("Attachment" => false));
    }
}